r = getOption("repos")
r["CRAN"] = "http://cran.us.r-project.org"
options(repos = r)

ifelse(!dir.exists("./lib"), dir.create("./lib"), FALSE)
install.packages("pracma")
install.packages("lubridate")
install.packages("anytime")
install.packages("signal")
install.packages("wmtsa")
install.packages("oce")
install.packages("dplyr")
install.packages("MESS")
install.packages("reticulate")
install.packages("gsubfn")
install.packages("ampd")
install.packages("psych")
install.packages("gtools")
install.packages("tidyr")
install.packages("promises")
install.packages("httpuv")
install.packages("fastmap")
install.packages("jsonlite")
install.packages("rgl")
install.packages("data.table")
install.packages("simstudy")
install.packages("xml2")
install.packages("askpass")
install.packages("openssl")
install.packages("tibble")
install.packages("tidyselect")
install.packages("purrr2")
install.packages("stringi")
install.packages("reshape2")
install.packages("colorspace")
install.packages("lazyeval")
install.packages("tidyverse")
install.packages("labeling")
install.packages("farver")
install.packages("ggplot2")
install.packages("lme4")
install.packages("pbkrtest")
install.packages("LMERConvenienceFunctions")
install.packages("splus2R")
install.packages("ifultools")
install.packages("pkgload")
install.packages("testthat")
install.packages("gsw")
install.packages("oce")
install.packages("mnormt")
install.packages("geepack")
install.packages("MESS")
install.packages("rappdirs")
install.packages("MESS")
install.packages("ellipsis")
install.packages("ipred")
install.packages("rpart")
install.packages("caret")
install.packages("pROC")  
install.packages("e1071")
install.packages("rJava")
install.packages("RWeka")
install.packages("party")
install.packages("partykit")
install.packages("zoo")
install.packages("sandwich")
install.packages("libcoin")
install.packages("coin")
install.packages("party")
install.packages("C50")
install.packages("RSNNS")
install.packages("kernlab")
install.packages("randomForest")
install.packages("fields")
install.packages("lifecycle")
install.packages("magrittr")
install.packages("Matrix")
install.packages("pillar")
install.packages("readxl")
install.packages("Rcpp")
install.packages("rlang")
install.packages("tibble")
install.packages("xlsx")
install.packages("xlsxjars")
install.packages("cellranger")
install.packages("arules")
install.packages("generics")
install.packages("gsw")
install.packages("proto")
install.packages("geeM", dependencies = TRUE) 
install.packages("ggformula", dependencies = TRUE)








